SELECT * FROM customer LIMIT 20;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating):: numeric,2) AS "Average Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Rating" DESC
LIMIT 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, AVG(purchase_amount) AS "Average Purchase Amount"
FROM customer 
WHERE shipping_type = 'Standard' OR shipping_type='Express'
GROUP BY shipping_type;

-- Another way is by using IN keyword and we can round the value also
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) AS "Total Customer",
	ROUND(AVG(purchase_amount),2) AS "Average Spend", 
	SUM(purchase_amount) AS "Total Revenue"
FROM customer
GROUP BY subscription_status
ORDER BY "Average Spend", "Total Revenue" DESC;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100.0*SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2 ) AS "Discount Rate"
FROM customer
GROUP BY item_purchased
ORDER BY "Discount Rate" DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
SELECT customer_segment, COUNT(*) AS "Total"
FROM

(SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment
FROM customer) 

GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
SELECT * FROM

(SELECT category,item_purchased, COUNT(*) AS "Purchases",
	ROW_NUMBER() OVER( PARTITION BY category ORDER BY COUNT(*) DESC) AS "Rank"
FROM customer
GROUP BY category,item_purchased) 

WHERE "Rank" <=3 ;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS "Repeated Buyers"
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;




--Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY (age_group)
ORDER BY total_revenue DESC;